// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "140320fd-4623-4263-8b53-d54758801416";

const char SSID[]               = "Beringin Camp";    // Network SSID (name)
const char PASS[]               = "lewatisaja2025";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "7sIe!k1MAAgohboWOjYgIBE77";    // Secret device password

// void onMulaiTanamChange();
void onRefillNutrisiChange();

float sisaNutrisi;
float suhu;
float tdsValue;
int umurTanaman;
bool refillNutrisi;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(sisaNutrisi, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(suhu, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tdsValue, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(umurTanaman, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(refillNutrisi, READWRITE, ON_CHANGE, onRefillNutrisiChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
